version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6

workflows:
  version: 2
  build:
    jobs:
      - docker-publish/publish
      - docker-publish/publish:
          tag: $CIRCLE_TAG
          filters:
            tags:
              only:
                - /.*/
            branches:
              ignore:
                - /.*/
